### ISSUE TITLE
Cell横向多个控件AutoLayout如何设置

### ISSUE THREAD

**Issue by 03128crz** [johnlui/AutoLayout#5]
你好，请问如下图Cell首行的应该怎么使用AutoLayout，
第一个view是个Label，长度根据内容变化
第二个view是ImageView+ Label，ImageView的长度也是根据里面的内容变化长度
两个view相距20px，
如果第一个view和第二view相加长度超过屏幕宽度，需要保持第二个view，然后第一个用xxx.....的形式展现。

我想了很久，好像只有手写代码才能实现这个需要。请问你有什么思路可以借鉴吗？谢谢:)

![image](https://cloud.githubusercontent.com/assets/3424553/13972943/9c6a0cfa-f0d8-11e5-853b-ab1d583b8840.png)

**Comment by johnlui** [comment]
1. 锁定间距20
2. 增加一个右边 ImageView 到右侧距离 >= 0
3. 给 ImageView 增加一个宽度约束，然后用代码调整这个约束的值，这样左边就会自动伸缩了。

**Comment by 03128crz** [comment]
那减28.8这个Label的约束如何加？谢谢

**Comment by 03128crz** [comment]
2.增加一个右边 ImageView 到右侧距离 >= 0
==》可以改成增加到减28.8这个Label到右侧距离>=0吗
我试了，会超过

**Comment by johnlui** [comment]
约束首先要完善，不完善的约束怎么设置都是无效的。

**Comment by 03128crz** [comment]
解决了，思路一下子开了，谢谢 :+1:
